apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: react-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
      - name: react-frontend
        image: jackfantasy/react-frontend:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react-frontend
  labels:
    name: react-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: react-frontend
